### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException: 'Unknown database 'issue1003'' 

### ISSUE THREAD

**Issue by nonoandy** [lauxjpn/Issue1003#1]
After getting the project and making sure connection string is correct I get the following

MySql.Data.MySqlClient.MySqlException: 'Unknown database 'issue1003''

(I have mariaDB 10.4.6)
  .UseMySql("server=localhost;port=3306;user=root;password=**********;database=Issue1003",
                    b => b.ServerVersion(new ServerVersion("10.4.6-MariaDB")))

**Comment by lauxjpn** [comment]
First of all, you probably want to post your issue on our official repository:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

You are posting this on my personal page here.

This sample code here on my repository (Issue1003) is related to an issue on our official repository:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1003

You will find the code and a general explanation over there.

Anyway, the error message says, that the database does not exist yet. My example code recreates this database on every execution, using the following two lines:

```c#
context.Database.EnsureDeleted();
context.Database.EnsureCreated();
```

If you have problems with the code, please post your full code (or upload your code to a repository and share that with us) to the original issue (https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1003).

**Comment by nonoandy** [comment]
This did fix the issues!
